# Generated by Django 5.2.17 on 2026-08-05 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_extended_hr_features'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='actual_return_date',
            field=models.DateField(blank=True, help_text='Actual day employee returned from leave', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='completion_comment',
            field=models.TextField(blank=True, help_text='Comment when marking leave as completed / returned to work'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='available_for_interns',
            field=models.BooleanField(default=False, help_text='If enabled, interns may use this leave type (optional)'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='pay_percentage',
            field=models.DecimalField(decimal_places=2, default=100, help_text='100 = full pay, 0 = no pay, 50 = half pay', max_digits=5),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='pay_policy',
            field=models.CharField(choices=[('full_pay', 'Full Pay'), ('no_pay', 'No Pay (Unpaid Leave)'), ('partial_pay', 'Partial Pay')], default='full_pay', help_text='Full pay, no pay, or partial pay for this leave type', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveDayException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('pay_policy', models.CharField(choices=[('full_pay', 'Full Pay'), ('no_pay', 'No Pay'), ('partial_pay', 'Partial Pay')], default='full_pay', max_length=20)),
                ('pay_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_exceptions', to='leave.leaverequest')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('leave_request', 'date')},
            },
        ),
    ]
