# Generated by Django 5.2.17 on 2026-08-05 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('core', '0002_extended_hr_features'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='excluded_from_attendance',
            field=models.BooleanField(default=False, help_text='Exclude from attendance stats (leave/holiday)'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_on_approved_leave',
            field=models.BooleanField(default=False, help_text='Auto-set when employee is on approved leave this day'),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='allow_manual_fallback',
            field=models.BooleanField(default=True, help_text='Allow manual check-in if biometric unavailable'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_in_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('biometric', 'Biometric'), ('qr', 'QR Code'), ('geolocation', 'GPS / Geolocation'), ('face_recognition', 'Face Recognition')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_out_method',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('biometric', 'Biometric'), ('qr', 'QR Code'), ('geolocation', 'GPS / Geolocation'), ('face_recognition', 'Face Recognition')], max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceCapture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capture_type', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('face_verify', 'Face Verification')], max_length=20)),
                ('photo', models.ImageField(upload_to='attendance/captures/%Y/%m/')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('biometric', 'Biometric'), ('qr', 'QR Code'), ('geolocation', 'GPS / Geolocation'), ('face_recognition', 'Face Recognition')], default='manual', max_length=20)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='attendance.attendancerecord')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.biometricdevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_captures', to='employees.employee')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceException',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_type', models.CharField(choices=[('late', 'Late Arrival'), ('early_departure', 'Early Departure'), ('missing_checkout', 'Missing Check-out'), ('gps_mismatch', 'GPS Location Mismatch'), ('other', 'Other')], default='late', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('minutes_affected', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_comment', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance_exceptions', to=settings.AUTH_USER_MODEL)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='attendance.attendancerecord')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchAttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_manual', models.BooleanField(default=True)),
                ('allow_gps', models.BooleanField(default=True)),
                ('allow_face', models.BooleanField(default=True)),
                ('allow_biometric', models.BooleanField(default=True)),
                ('require_photo', models.BooleanField(default=False)),
                ('require_gps', models.BooleanField(default=False)),
                ('geofence_radius_meters', models.PositiveIntegerField(default=200)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
